### PR TITLE
Upgrade node-sass.

### PR DESCRIPTION
**Pull request by kid-icarus**
Need this for Node 8+ 🙏

### CODE REVIEW

**Comment by sidewalksalsa** [comment]
Need this to be able to use latest Sass lang features...

**Comment by sidewalksalsa** [comment]
@dgbeck ^^

**Comment by dgbeck** [comment]
thx for the ping @sidewalksalsa , had not seen this. published @ v1.0.0

**Comment by sidewalksalsa** [comment]
No problem, thanks @dgbeck!

**Pull request merged**
